#!/usr/bin/env python3
"""Export Apps Script data as paste-ready Supabase SQL.

Goal: keep migration dead-simple for beginners who want to use Supabase SQL Editor.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.parse
import urllib.request
from typing import Any, Dict, List


def env(name: str, required: bool = True, default: str = "") -> str:
    value = os.environ.get(name, default).strip()
    if required and not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def get_apps_script_json(base_url: str, query: Dict[str, str]) -> Dict[str, Any]:
    url = f"{base_url}?{urllib.parse.urlencode(query)}"
    req = urllib.request.Request(url, method="GET")
    with urllib.request.urlopen(req, timeout=30) as resp:
        payload = resp.read().decode("utf-8")
    data = json.loads(payload)
    if not data.get("success"):
        raise RuntimeError(f"Apps Script error for action={query.get('action')}: {data.get('error')}")
    return data


def normalize_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes"}


def sql_string(value: Any) -> str:
    if value is None:
        return "NULL"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def room_values_sql(rows: List[Dict[str, Any]]) -> List[str]:
    values = []
    for row in rows:
        floor = str(row.get("층", "")).strip().upper()
        if not floor:
            continue
        room_id = str(row.get("회의실ID", floor)).strip() or floor
        name = str(row.get("이름", "")).strip() or floor
        is_active = "true" if normalize_bool(row.get("활성화", True)) else "false"
        values.append(f"({sql_string(room_id)}, {sql_string(floor)}, {sql_string(name)}, {is_active})")
    return values


def reservation_values_sql(rows: List[Dict[str, Any]]) -> List[str]:
    values = []
    for row in rows:
        rid = str(row.get("예약ID", "")).strip()
        date = str(row.get("날짜", "")).strip()
        floor = str(row.get("층", "")).strip().upper()
        start_time = str(row.get("시작시간", "")).strip()
        end_time = str(row.get("종료시간", "")).strip()
        if not (rid and date and floor and start_time and end_time):
            continue

        team_name = str(row.get("팀명", "")).strip()
        user_name = str(row.get("예약자", "")).strip()
        created_at_raw = str(row.get("생성일시", "")).strip()
        created_at = sql_string(created_at_raw) if created_at_raw else "now()"

        # Apps Script 공개 조회 API에서 비밀번호해시를 제공하지 않으므로 placeholder 사용.
        password_hash = "__PHASE_B_PLACEHOLDER__"

        values.append(
            "(" + ", ".join(
                [
                    sql_string(rid),
                    sql_string(date),
                    sql_string(floor),
                    sql_string(start_time),
                    sql_string(end_time),
                    sql_string(team_name),
                    sql_string(user_name),
                    sql_string(password_hash),
                    created_at,
                ]
            ) + ")"
        )
    return values


def build_sql(rooms: List[Dict[str, Any]], reservations: List[Dict[str, Any]]) -> str:
    room_values = room_values_sql(rooms)
    reservation_values = reservation_values_sql(reservations)

    lines = [
        "-- Generated by scripts/export_supabase_insert_sql.py",
        "-- Paste this SQL into Supabase SQL Editor and run.",
        "",
        "begin;",
        "",
    ]

    if room_values:
        lines.extend(
            [
                "insert into rooms (id, floor, name, is_active)",
                "values",
                "  " + ",\n  ".join(room_values),
                "on conflict (id) do update set",
                "  floor = excluded.floor,",
                "  name = excluded.name,",
                "  is_active = excluded.is_active,",
                "  updated_at = now();",
                "",
            ]
        )
    else:
        lines.extend(["-- rooms: no rows", ""])

    if reservation_values:
        lines.extend(
            [
                "insert into reservations (id, date, floor, start_time, end_time, team_name, user_name, password_hash, created_at)",
                "values",
                "  " + ",\n  ".join(reservation_values),
                "on conflict (id) do update set",
                "  date = excluded.date,",
                "  floor = excluded.floor,",
                "  start_time = excluded.start_time,",
                "  end_time = excluded.end_time,",
                "  team_name = excluded.team_name,",
                "  user_name = excluded.user_name,",
                "  password_hash = excluded.password_hash;",
                "",
            ]
        )
    else:
        lines.extend(["-- reservations: no rows", ""])

    lines.extend(
        [
            "commit;",
            "",
            "-- 검증",
            "select count(*) as rooms_count from rooms;",
            "select count(*) as reservations_count from reservations;",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    try:
        apps_script_url = env("APPS_SCRIPT_URL")
        proxy_secret = env("PROXY_SHARED_SECRET", required=False)
        admin_token = env("ADMIN_TOKEN", required=False)
        output_path = env("OUTPUT_SQL_PATH", required=False, default="supabase_import.sql")

        room_query: Dict[str, str] = {"action": "getRooms"}
        if admin_token:
            room_query["includeInactive"] = "1"
            room_query["adminToken"] = admin_token
        if proxy_secret:
            room_query["proxySecret"] = proxy_secret

        reservation_query: Dict[str, str] = {"action": "getReservations"}
        if proxy_secret:
            reservation_query["proxySecret"] = proxy_secret

        print("[step] fetch rooms")
        rooms = get_apps_script_json(apps_script_url, room_query).get("data", [])
        print(f"[info] rooms rows={len(rooms)}")

        print("[step] fetch reservations")
        reservations = get_apps_script_json(apps_script_url, reservation_query).get("data", [])
        print(f"[info] reservations rows={len(reservations)}")

        sql = build_sql(rooms, reservations)
        with open(output_path, "w", encoding="utf-8") as fp:
            fp.write(sql)

        print(f"[done] wrote SQL: {output_path}")
        print("[warn] password_hash는 placeholder로 채워집니다 (Phase B 읽기 전환용).")
        return 0
    except Exception as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
