-- Generated by scripts/export_supabase_insert_sql.py
-- Paste this SQL into Supabase SQL Editor and run.

begin;

insert into rooms (id, floor, name, is_active)
values
  ('6F', '6F', '회의실', true),
  ('7F', '7F', '회의실', true),
  ('8F', '8F', '회의실', true),
  ('9F', '9F', '회의실', true)
on conflict (id) do update set
  floor = excluded.floor,
  name = excluded.name,
  is_active = excluded.is_active,
  updated_at = now();

insert into reservations (id, date, floor, start_time, end_time, team_name, user_name, password_hash, created_at)
values
  ('d02fb2cb8907', '2026-02-18', '9F', '11:00', '12:00', 'ㅂㅈㄷ', 'ㅂㄱㅂㄱ', '__PHASE_B_PLACEHOLDER__', '2026-02-13T14:24:38.706Z'),
  ('d230f415d68b', '2026-02-16', '9F', '14:30', '15:30', 'ㅂㅂㅈㄷㅂㄷㅂ', 'ㅂㄷㅂㄷㅂㅂ', '__PHASE_B_PLACEHOLDER__', '2026-02-14T08:19:58.643Z'),
  ('16bda83a81fc', '2026-02-20', '9F', '15:00', '16:00', '호호호', '고고고', '__PHASE_B_PLACEHOLDER__', '2026-02-14T08:31:34.514Z'),
  ('58befb010e67', '2026-02-19', '9F', '10:00', '11:00', '고고고', '도도도', '__PHASE_B_PLACEHOLDER__', '2026-02-14T08:39:08.756Z'),
  ('a661e4962ddb', '2026-02-20', '9F', '16:00', '17:00', '버버ㅓㅂ', '저저저', '__PHASE_B_PLACEHOLDER__', '2026-02-14T08:54:43.234Z')
on conflict (id) do update set
  date = excluded.date,
  floor = excluded.floor,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  team_name = excluded.team_name,
  user_name = excluded.user_name,
  password_hash = excluded.password_hash;

commit;

-- 검증
select count(*) as rooms_count from rooms;
select count(*) as reservations_count from reservations;